swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: API First Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

definitions:
  People:
    type: object
    required:
      - fname
      - lname
    properties:
      fname:
        type: string
        description: First name of person to create
      lname:
        type: string
        description: Last name of person to create
  PeopleList:
    type: array
    items:
      properties:
        fname:
          type: string
        lname:
          type: string

paths:
  /people:
    get:
      operationId: resources.people.read_all
      tags:
        - people
      summary: The people data structure supported by the server application
      description: Read the list of people
      parameters:
        - name: limit
          in: query
          type: integer
          description: Number of people to get from people
          required: false
        - name: offset
          in: query
          type: integer
          description: Offset from beginning of list where to start gathering people
          required: false
      responses:
        200:
          description: Successful read people list operation
          schema:
            $ref: '#/definitions/PeopleList'
    post:
      operationId: resources.people.create
      tags:
        - people
      summary: Create a person and add it to the people list
      description: Create a new person in the people list
      parameters:
        - name: person
          in: body
          description: Person to create
          required: true
          schema:
            $ref: "#/definitions/People"
      responses:
        201:
          description: Successfully create person to create