swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: API First Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

definitions:
  People:
    type: object
    required:
      - fname
      - lname
    properties:
      fname:
        type: string
        description: First name of person to create
      lname:
        type: string
        description: Last name of person to create